### ISSUE TITLE
[enhance] upload组件优化

### ISSUE THREAD

**Issue by lidongbest5** [36node/react-upload#2]
### 简介

upload组件还需要一些优化，除了裁剪功能其他的antd的upload组件都已经实现，这里只需要把相应的参数变为当前组件可配置的就行了

antd upload地址：https://ant.design/components/upload-cn/

优化需求:

1.上传文件大小限制
2.上传文件类型的限制
3.上传的listtype配置
4.多文件的上传
5.文件上传后的预览以及initial的files的展示
6.图片裁剪功能，除了裁剪框，这里最好是后边的图片也是可拖动缩放的，可以多看些相关组件，多沟通
7.其他的如果有自己发现还没提到的也可以优化

### 截止日期（选填）

领取后5天

**Comment by zzswang** [comment]
支持一个 前缀路径

**Comment by wfnuser** [comment]
上传listtype 我的理解直接传入accept是不是更好？

**Comment by wfnuser** [comment]
1. done
2. 上传文件类型 我的理解直接传入accept是不是更好？
3. 已经透传
4. done
5. 如果listtype为"picture-card"即可预览
6. 这个要研究一下
7. 加了一个最大文件数的限制，理论上来说超过最大文件数应该上传按钮会消失，但实际上只是里面的部分内容消失了 可能和uploader里仍然有reactdom有关，目前只是在封装的组件内部屏蔽了this.props.children @lidongbest5 @zzswang 可以帮忙看一下

**Comment by wfnuser** [comment]
另外，改了一下storybook的配置 原有的配置没有办法加载antd的样式 因为用了less
